### ISSUE TITLE
Login workflow

### ISSUE THREAD

**Issue by mz106** [mz106/climbing-buddy-fe#11]
A design of the workflow for the UX on login

**Comment by bar-alex** [comment]
We can use the ones we have built for our final project, have a look at this module
https://github.com/bar-alex/CodeNation-FinalProject-FrontEnd/blob/c1c0dfe0a77f4073418499ef6de74559c2a6d214/src/util/utilUser.js

They match for ur backend, but they can't be that different I imagine

**Comment by mz106** [comment]
I'm not sure yet, I'd have to check. However, this is for a design doc rather than code, working out the workflow which will define direction of user interactions/data transfer and the names of the functions.

**Comment by bar-alex** [comment]
- The login form (user + password inputs) could be in the navbar, like we did in our project, or in a div on the landing page
- The login form will call a function _userLogin(userObj, setUser)_ with an object { username, password } and a setter to set the state _user_ - an object that holds the info of the user like full name, username, email, etc

- If the login is unsuccessful a message (alert / toast / inline text) should be displayed to alert the user login was not successful
- If the login was successful 
  - The login form disappears and a message "Wellcome <name of user>" will be displayed in the navbar, 
  - Next to it, a button/link to logout/signout that will logout the user (clear user object state and remove token from localStorage) 
  - Next to it, will be a button/link that will show user's info and allow to update the user's info or delete the user from the system
  
- Once successfully logged in, the app receives the authorization token and an object with user's information
  - It will save the object with the user data in a state - it will be available and used throughout the entire app
  - It will save the token in the browser's localStorage, 
  - The user's choice to stay be kept logged in between sessions or not should be stored in localstorage as well, this will affect if the system will auto-login the user on a refresh, or when the user returns to the app at a later time
  - _Note:_ The authorization token can hold data about viability, so if the user chooses to stay logged in, a 7 or 30 days viability could be attached to the token; 
  - _Note:_ These are possible using JSON Web Token, I'm not sure what you can do with Passport
- This concludes the login process.

**Comment by mz106** [comment]
JWTs can be used with Passport. Could you please document this as a workflow diagram and add it to the repo?

**Comment by bar-alex** [comment]
The workflow diagram was done and merged with the documentation branch.
